name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_URL }}

      - name: Build, Tag, and Push Docker Image
        run: |
          IMAGE_TAG=${{ github.run_number }}
          docker build -t ${{ secrets.ECR_REPO_URL }}:$IMAGE_TAG -f app/Dockerfile ./app
          docker push ${{ secrets.ECR_REPO_URL }}:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Configure Kubectl
        run: |
          aws eks --region ap-south-1 update-kubeconfig --name my-eks-cluster

      - name: Deploy to Kubernetes
        run: |
          sed -i "s|<ECR_REPO_URL>|${{ secrets.ECR_REPO_URL }}|g" k8s/deployment.yaml
          sed -i "s|<IMAGE_TAG>|$IMAGE_TAG|g" k8s/deployment.yaml
          kubectl apply -f k8s/
          kubectl rollout status deployment/node-app
